### ISSUE TITLE
Support full name in file error_code_config.yml

### ISSUE THREAD

**Issue by ckunki** [exasol/error-code-crawler-maven-plugin#97]
The discussion In ticket In IntRef led to 2 options : O1) MVP O2) Full implementation. 

The current ticket describes MVP:
* Enable developers to add a `name` for each error-tag in file `error_code_config.yml`
* Update tools to not break when `name` is added

After the current ticket is implemented additionally requires to update [project-keeper](https://github.com/exasol/project-keeper) templates to use latest version of ECM, see follow-up-tasks below.

### Tasks 
Update [error-code-crawler-maven-plugin](https://github.com/exasol/error-code-crawler-maven-plugin/) (ECM) to
* require entry `name` for each error-tag in file `error_code_config.yml` and
* to [deserialize](https://github.com/exasol/error-code-crawler-maven-plugin/blob/main/src/main/java/com/exasol/errorcodecrawlermavenplugin/config/ErrorCodeConfigReader.java#L71) it into the internal class [ErrorCodeConfig](https://github.com/exasol/error-code-crawler-maven-plugin/blob/main/src/main/java/com/exasol/errorcodecrawlermavenplugin/config/ErrorCodeConfig.java)

Sample content for file `error_code_config.yml`:

```yaml
error-tags:
  EITFJ:
    # Full name from which the short tag is derived from
    name: Extension Integration Test Framework Java
    packages:
      - com.exasol.extensionmanager.itest
    highest-index: 42
```

### Follow-up changes

Update [project-keeper](https://github.com/exasol/project-keeper) templates to use latest version of ECM

For affected projects: Describe
* Update to latest version of ECM will not be backwards compatible
* Required changes in file `error_code_config.yml`
